osx_image: xcode7.2
language: objective-c
script:
  - xcodebuild -workspace CINN.xcworkspace -scheme TrendCore -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6' test
  - xcodebuild -workspace CINN.xcworkspace -scheme TrendViewModel -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6' test
  - xcodebuild -workspace CINN.xcworkspace -scheme TrendViewController -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6' test